src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "platform/",
        views.PermanentRedirectView.as_view(
            url="https://hosting.terminusgps.com/", query_string=True
        ),
        name="platform",
    ),
    path(
        "source/",
        views.PermanentRedirectView.as_view(
            url="https://github.com/terminusgps/terminusgps-site/"
        ),
        name="source code",
    ),
    path(
        "apps/ios/",
        views.PermanentRedirectView.as_view(
            url="https://apps.apple.com/us/app/terminus-gps-mobile/id1419439009"
        ),
        name="ios app",
    ),
    path(
        "apps/android/",
        views.PermanentRedirectView.as_view(
            url="https://play.google.com/store/apps/details?id=com.terminusgps.track&pcampaignid=web_share"
        ),
        name="android app",
    ),
    path(
        "",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/home.html",
            extra_context={
                "title": "Home",
                "subtitle": "In God we trust, all others we track",
            },
        ),
        name="home",
    ),
    path(
        "features/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/features.html",
            extra_context={
                "title": "Features",
                "subtitle": "Your entire fleet, at your fingertips",
            },
        ),
        name="features",
    ),
    path(
        "about/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/about.html",
            extra_context={
                "title": "About",
                "subtitle": "Why we do what we do",
            },
        ),
        name="about",
    ),
    path(
        "contact/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/contact.html",
            extra_context={"title": "Contact", "subtitle": "Drop us a line"},
        ),
        name="contact",
    ),
    path(
        "privacy/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/privacy.html",
            extra_context={
                "title": "Privacy Policy",
                "subtitle": "How we use your data",
            },
        ),
        name="privacy",
    ),
    path(
        "terms/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/terms.html",
            extra_context={
                "title": "Terms & Conditions",
                "subtitle": "You agree to these by using Terminus GPS services",
            },
        ),
        name="terms",
    ),
    path(
        "faq/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/faq.html",
            extra_context={
                "title": "Frequently Asked Questions",
                "subtitle": "With frequently cited answers",
            },
        ),
        name="faq",
    ),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path(
        "logout/",
        views.HtmxTemplateView.as_view(
            template_name="terminusgps/logout.html",
            extra_context={"title": "Logout"},
        ),
        name="logout",
    ),
    path(
        "logged_out/",
        views.LogoutView.as_view(extra_context={"title": "Logged Out"}),
        name="logged out",
    ),
    path(
        "payments/",
        include("terminusgps_payments.urls", namespace="terminusgps_payments"),
    ),
    path(
        "",
        include("terminusgps_manager.urls", namespace="terminusgps_manager"),
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

terminusgps_manager/urls.py
import terminusgps_payments
from django.urls import path, reverse_lazy
from django.utils.translation import gettext_lazy as _

from . import views

app_name = "terminusgps_manager"
urlpatterns = [
    path(
        "dashboard/",
        views.TerminusGPSManagerTemplateView.as_view(
            template_name="terminusgps_manager/dashboard.html",
            extra_context={"title": "Dashboard"},
        ),
        name="dashboard",
    ),
    path(
        "account/",
        views.TerminusGPSManagerTemplateView.as_view(
            template_name="terminusgps_manager/account.html",
            extra_context={"title": "Account"},
        ),
        name="account",
    ),
    path(
        "subscriptions/",
        views.TerminusGPSManagerTemplateView.as_view(
            template_name="terminusgps_manager/subscriptions.html",
            extra_context={"title": "Subscription"},
        ),
        name="subscriptions",
    ),
    path(
        "subscriptions/new/",
        views.TerminusGPSManagerSubscriptionCreateView.as_view(
            template_name="terminusgps_payments/subscription_create.html",
            name=_("Terminus GPS Subscription"),
            success_url=reverse_lazy(
                "terminusgps_manager:create subscriptions success"
            ),
        ),
        name="create subscriptions",
    ),
    path(
        "subscriptions/new/success/",
        views.SubscriptionCreateSuccessView.as_view(),
        name="create subscriptions success",
    ),
    path(
        "subscriptions/<int:pk>/update/",
        terminusgps_payments.views.SubscriptionUpdateView.as_view(
            template_name="terminusgps_payments/subscription_update.html"
        ),
        name="update subscriptions",
    ),
    path(
        "subscriptions/<int:pk>/delete/",
        views.TerminusGPSManagerSubscriptionDeleteView.as_view(
            template_name="terminusgps_payments/subscription_delete.html"
        ),
        name="delete subscriptions",
    ),
]

terminusgps_manager/views.py
import logging
import typing

from dateutil.relativedelta import relativedelta
from django import forms
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import ngettext
from django.views.decorators.cache import cache_control
from django.views.generic import TemplateView
from django.views.generic.base import ContextMixin
from terminusgps.mixins import HtmxTemplateResponseMixin
from terminusgps.wialon.session import WialonAPIError, WialonSession
from terminusgps_payments.models import Subscription
from terminusgps_payments.views.generic import AuthorizenetDeleteView
from terminusgps_payments.views.subscriptions import SubscriptionCreateView

from .models import TerminusGPSCustomer

logger = logging.getLogger(__name__)


class TerminusGPSCustomerContextMixin(ContextMixin):
    """Adds ``customer`` to the view context."""

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        try:
            customer = TerminusGPSCustomer.objects.get(user=self.request.user)
        except TerminusGPSCustomer.DoesNotExist:
            customer = None

        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = customer
        return context


@method_decorator(cache_control(private=True), name="dispatch")
class TerminusGPSManagerTemplateView(
    LoginRequiredMixin,
    TerminusGPSCustomerContextMixin,
    HtmxTemplateResponseMixin,
    TemplateView,
):
    content_type = "text/html"
    http_method_names = ["get"]


class SubscriptionCreateSuccessView(TerminusGPSManagerTemplateView):
    template_name = "terminusgps_payments/subscription_create_success.html"


class TerminusGPSManagerSubscriptionDeleteView(AuthorizenetDeleteView):
    model = Subscription

    def get_success_url(self) -> str:
        return reverse("terminusgps_manager:create subscriptions")

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        try:
            customer = TerminusGPSCustomer.objects.get(user=self.request.user)
            start_date = customer.subscription.start_date
            end_date = start_date + relativedelta(months=1)
            with WialonSession(token=settings.WIALON_TOKEN) as session:
                resp = customer.wialon_account.get_account_data(session)
                curr = int(resp["daysCounter"])
                days = (end_date - start_date).days - curr
                customer.wialon_account.enable(session)
                customer.wialon_account.update_flags(session, flags=0x20)
                customer.wialon_account.do_payment(
                    session,
                    days=days,
                    desc=f"terminusgps_manager: Added {days} {ngettext('day', 'days', days)}.",
                )
            super().form_valid(form=form)
            return HttpResponseRedirect(self.get_success_url())
        except (TerminusGPSCustomer.DoesNotExist, WialonAPIError) as error:
            form.add_error(
                None,
                ValidationError(
                    "%(error)s", code="invalid", params={"error": error}
                ),
            )
            return self.form_invalid(form=form)


class TerminusGPSManagerSubscriptionCreateView(SubscriptionCreateView):
    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        super().setup(request, *args, **kwargs)
        try:
            self.customer = (
                TerminusGPSCustomer.objects.get(user=request.user)
                if hasattr(request, "user")
                else None
            )
            self.amount = self.customer.grand_total
        except TerminusGPSCustomer.DoesNotExist:
            self.customer = None

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        sub_total = (
            self.customer.sub_total if self.customer is not None else None
        )
        tax_total = (
            self.customer.tax_total if self.customer is not None else None
        )
        grand_total = (
            self.customer.grand_total if self.customer is not None else None
        )

        context = super().get_context_data(**kwargs)
        context["sub_total"] = sub_total
        context["tax_total"] = tax_total
        context["grand_total"] = grand_total
        return context

    def form_valid(self, form: forms.ModelForm) -> HttpResponse:
        try:
            response = super().form_valid(form=form)
            customer = TerminusGPSCustomer.objects.get(user=self.request.user)
            customer.subscription = self.object
            customer.save(update_fields=["subscription"])
            with WialonSession(token=settings.WIALON_TOKEN) as session:
                customer.wialon_account.enable(session)
                customer.wialon_account.update_flags(session, flags=-0x20)
            return response
        except (TerminusGPSCustomer.DoesNotExist, WialonAPIError):
            return response

terminusgps_manager/templates/terminusgps_manager/account.html
{% extends "terminusgps/layout.html" %}
{% partialdef main %}
<div
    class="group flex flex-col border rounded border-stone-400 dark:border-stone-900 drop-shadow-sm"
    hx-get="{% url 'terminusgps_payments:list payment profiles' %}"
    hx-target="#payment-profiles"
    hx-trigger="load once"
    hx-indicator="#payment-profiles-indicator"
>
    <div class="flex flex-col gap-4 p-8 bg-stone-50 dark:bg-stone-800 rounded">
        <div
            id="payment-profiles"
            class="peer relative flex flex-col gap-4 order-last"
        >
            <button
                type="button"
                class="flex w-full cursor-not-allowed items-center justify-center gap-2 rounded border border-terminus-red-900 bg-terminus-red-800 p-2 text-center text-white transition-colors duration-300 ease-in-out hover:bg-terminus-red-400"
                disabled
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                <p>Add Payment Profile</p>
            </button>
        </div>
        <div class="flex items-center gap-2">
            <h3 class="text-xl md:text-2xl text-terminus-red-700 font-semibold dark:text-terminus-red-200">Payment Profiles</h3>
            <svg id="payment-profiles-indicator" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 animate-spin htmx-indicator">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
            </svg>
        </div>
    </div>
</div>
<div
    class="flex flex-col border rounded border-stone-400 dark:border-stone-900 drop-shadow-sm"
    hx-get="{% url 'terminusgps_payments:list address profiles' %}"
    hx-target="#address-profiles"
    hx-trigger="load once"
    hx-indicator="#address-profiles-indicator"
>
    <div class="flex flex-col gap-4 p-8 bg-stone-50 dark:bg-stone-800 rounded">
        <div
            id="address-profiles"
            class="peer relative flex flex-col gap-4 order-last"
        >
            <button
                type="button"
                class="flex w-full cursor-not-allowed items-center justify-center gap-2 rounded border border-terminus-red-900 bg-terminus-red-800 p-2 text-center text-white transition-colors duration-300 ease-in-out hover:bg-terminus-red-400"
                disabled
            >
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
                <p>Add Address Profile</p>
            </button>
        </div>
        <div class="flex gap-2 items-center">
            <h3 class="text-xl md:text-2xl text-terminus-red-700 font-semibold dark:text-terminus-red-200">Address Profiles</h3>
            <svg id="address-profiles-indicator" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 animate-spin htmx-indicator">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
            </svg>
        </div>
    </div>
</div>
{% endpartialdef main %}
{% block content %}
{% partial main %}
{% endblock content %}

terminusgps_manager/templates/terminusgps_manager/create_subscription.html
{% extends "terminusgps/layout.html" %}
{% block content %}
{% include "terminusgps_manager/partials/_create_subscription.html" %}
{% endblock content %}

terminusgps_manager/templates/terminusgps_manager/dashboard.html
{% extends "terminusgps/layout.html" %}
{% block content %}
{% partialdef partial inline %}
<div id="greeting" class="flex flex-col p-2 gap-2 text-center">
    <h3 class="font-semibold text-gray-900">Hey, {{ request.user.first_name|default:'there' }}!</h3>
    <p class="text-gray-600">It's {% now 'F jS, Y' %}</p>
</div>
<div id="links" class="flex flex-col gap-4" hx-boost="true">
    <a href="{% url 'terminusgps_manager:account' %}" class="flex items-center justify-between gap-2 rounded border-2 border-terminus-red-800 bg-terminus-red-500 p-4 text-gray-100 transition-colors duration-300 ease-in-out hover:bg-terminus-red-200">
        <div class="flex items-center gap-4">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
            </svg>
            <p class="font-semibold tracking-wide uppercase">Account</p>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="m5.25 4.5 7.5 7.5-7.5 7.5m6-15 7.5 7.5-7.5 7.5" />
        </svg>
    </a>
    <a href="{% url 'terminusgps_manager:subscriptions' %}" class="flex items-center justify-between gap-2 rounded border-2 border-terminus-red-800 bg-terminus-red-500 p-4 text-gray-100 transition-colors duration-300 ease-in-out hover:bg-terminus-red-200">
        <div class="flex items-center gap-4">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 3.75v16.5M2.25 12h19.5M6.375 17.25a4.875 4.875 0 0 0 4.875-4.875V12m6.375 5.25a4.875 4.875 0 0 1-4.875-4.875V12m-9 8.25h16.5a1.5 1.5 0 0 0 1.5-1.5V5.25a1.5 1.5 0 0 0-1.5-1.5H3.75a1.5 1.5 0 0 0-1.5 1.5v13.5a1.5 1.5 0 0 0 1.5 1.5Zm12.621-9.44c-1.409 1.41-4.242 1.061-4.242 1.061s-.349-2.833 1.06-4.242a2.25 2.25 0 0 1 3.182 3.182ZM10.773 7.63c1.409 1.409 1.06 4.242 1.06 4.242S9 12.22 7.592 10.811a2.25 2.25 0 1 1 3.182-3.182Z" />
            </svg>
            <p class="font-semibold tracking-wide uppercase">Subscription</p>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-8">
            <path stroke-linecap="round" stroke-linejoin="round" d="m5.25 4.5 7.5 7.5-7.5 7.5m6-15 7.5 7.5-7.5 7.5" />
        </svg>
    </a>
</div>
{% endpartialdef partial %}
{% endblock content %}

terminusgps_manager/templates/terminusgps_manager/subscriptions.html
{% extends "terminusgps/layout.html" %}
{% block content %}
{% partialdef partial inline %}
<div class="@container p-4 flex flex-col gap-4" hx-indicator="#loading">
    <div
        id="subscription"
        class="p-4 flex flex-col gap-4 bg-stone-50 border rounded border-stone-400 drop-shadow-sm @md:p-8"
        hx-get="{% if customer.subscription != None %}{% url 'terminusgps_payments:detail subscriptions' customer.subscription.pk %}{% else %}{% url 'terminusgps_manager:create subscriptions' %}{% endif %}"
        hx-target="this"
        hx-trigger="load once"
    ></div>
</div>
{% endpartialdef partial %}
{% endblock content %}